spring:
  application:
    name: coupon-concurrency
  profiles:
    default: local
  jpa:
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
server:
  error:
    include-stacktrace: never
    include-message: always
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:coupon_db
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: dev
  main:
    datasource:
      hikari:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:43306/coupon_db
        username: root
        password: 1234
        connection-timeout: 10000
        maximum-pool-size: 10
  lock:
    datasource:
      hikari:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:43306/coupon_db
        username: root
        password: 1234
        connection-timeout: 10000
        maximum-pool-size: 100
  data:
    redis:
      host: localhost
      port: 6379
      username:
      password: