spring:
  application:
    name: coupon-concurrency
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coupon_db
    username: sa
    password:
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

server:
  error:
    include-stacktrace: never
